language: r
r:
  - oldrel
  - release
  
cache: packages

os:
  - linux
  - osx
  
before_install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("git2r", repos = "http://cran.rstudio.com")'

# before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown#1276")'
# deploy:
#   provider: script
#   script: Rscript -e 'pkgdown::deploy_site_github()'
#   skip_cleanup: true