language: r
r:
  - oldrel
  - release
  - devel
  
cache: packages

os:
  - linux
  - osx
  
sudo: false

before_install:
  - Rscript -e 'install.packages("devtools", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("git2r", repos = "http://cran.rstudio.com")'